---
title: About
---

= About the author

Hello! I'm Gabriel Arazas.
Just a hobbyist on software development and programming.
I'm also an aspiring engineer upping the ante on my mathematics skills.

I also like the following stuff:

* 3D modelling, especially when done computationally.
* Free and open source software as it is relevant for a low-income worker.
* Creative coding as a form of stress-relieving.
* Linux for that l33t hacker rep as well as a lot of good applications that come with it.
* Mathematics (I'm working on this one).
* Music from the classical and metal (and https://en.wikipedia.org/wiki/Symphonic_metal[both]) but open-minded for other things.
footnote:[Feel free to randomly DM me about your recent tastes on music.]
* Software reproducibility as a user-facing feature.
* Pixel art because it's just images on very low resolution and my ancient hardware is happy to render it for me.
* Writing as I'm trying to like documenting my projects.

I also https://www.youtube.com/channel/UCuMiU9bzATu5oTp-vhOlL2Q[create some crap music] but you're definitely not here for that.

If you want a way on getting contact with me, you can shoot an email at `foo.dogsquared{at}gmail{dot}com`.

I'm open to your shenanigans as long as it's about dev-related or hobby-related (and legal, of course).

Welp, see you on the field, internet stranger. :)

